name: Send File Changes

on:
  push:
    branches:
      - main  # Adjust to your branch as necessary
    paths: 
      - '**.mdx'  # Only trigger for changes in .mdx files

jobs:
  send-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send File Changes to Webhook
      uses: Lamatic/Index-to-lamatic@v1.6
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_key: ${{ secrets.WEBHOOK_KEY }}
        github_ref: ${{ github.ref }}
        file_type: "mdx"
        mode: "full-refresh"  # or "full-refresh"
        verbose: "true"  # or "false"

name: Lamatic Index Flow

on:
  push:
    branches:
      - main  # Replace with your branch if necessary
    paths: 
      - '**.mdx'  # Adjust to only trigger for changes to specific file types

jobs:
  send-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send File Changes to Webhook
      uses: Lamatic/Index-to-lamatic@v1.6  # Uses action
      with:
        webhook_url: ${{ https://hooks.lamatic.ai/hook/a388037b-9885-4c51-9569-3e1556df8c57 }}  # Replace with your secret
        webhook_key: ${{ a388037b-9885-4c51-9569-3e1556df8c57}}   # Replace with your secret
        github_ref: ${{ github.ref }}
        file_type: "mdx"  # Adjust the file type as needed
        mode: "incremental"  # or "full-refresh"
        verbose: "true"  # or "false"
